(() => {
  const $ = id => document.getElementById(id);
  const Recognition = window.SpeechRecognition || window.webkitSpeechRecognition;
  let recognition, listening = false, starting = false, browserStopped = false, micReady = false, scheduleStopTimer = null, toastTimer = null, prayerToastTimer = null, quoteTimer = null, quoteIndex = 0, prayerData = null, heardBuffer = "", listenStartedAt = 0, lastAlert = 0, screenStream = null, screenTimer = null, screenMonitoring = false, screenLastFrame = null, screenChangeCount = 0, screenLastAlert = 0, screenSelection = null, screenDrag = null;
  const quotes = [["فَإِنَّ مَعَ الْعُسْرِ يُسْرًا", "", "آية — سورة الشرح، رقم 5", "verse"],["اللهم لا سهل إلا ما جعلته سهلًا", "O Allah, nothing is easy except what You make easy."],["Keep going. You are closer than you think.", "واصل. أنت أقرب مما تتوقع."],["Focus on progress, not perfection.", "ركّز على التقدم لا الكمال."],["Small consistent steps create big results.", "الخطوات الصغيرة المستمرة تصنع نتائج كبيرة."],["Ask questions early; confusion grows in silence.", "اسأل مبكرًا؛ فالالتباس يكبر مع الصمت."],["Your calendar shows your priorities.", "تقويمك يكشف أولوياتك."],["Do the important task before the urgent noise.", "أنجز المهم قبل أن يسرقك ضجيج العاجل."],["A clear note saves a future hour.", "ملاحظة واضحة توفر ساعة في المستقبل."],["Rest is part of disciplined work, not a reward for burnout.", "الراحة جزء من العمل المنضبط، وليست مكافأة بعد الإرهاق."],["Be reliable: do what you said you would do.", "كن موثوقًا: افعل ما قلت إنك ستفعله."],["Learn the skill, then practice it in public.", "تعلم المهارة، ثم طبّقها أمام الآخرين."],["Good work becomes visible when you communicate it clearly.", "العمل الجيد يظهر عندما تشرحه بوضوح."],["اللهم فرّج همّ المهمومين من المسلمين، واشف مرضاهم، وارحم موتاهم.", "", "آمين", "prayer"],["اللهم ارزق من تأخر عنه الذرية ذرية صالحة، واجعلها قرة عين له.", "", "آمين", "prayer"],["اللهم أغنِ الفقير، وارزقه من واسع فضلك، وأغنه بحلالك عن حرامك.", "", "آمين", "prayer"],["اللهم ارحم اليتيم، واجبر قلبه، وهيئ له من أمره رشدًا ورحمة.", "", "آمين", "prayer"],["اللهم اغفر لموتى المسلمين، وارحمهم، ونوّر قبورهم، واجعل الجنة دارهم.", "", "آمين", "prayer"],["رَبِّ زِدْنِي عِلْمًا", "", "آية — سورة طه، رقم 114", "verse"]];
  const status = text => { $("listen-status").textContent = text; };
  const normalize = value => value.toLowerCase().replace(/[\u064B-\u065F\u0670]/g, "").replace(/[إأآ]/g, "ا").replace(/ى/g, "ي").replace(/[^\p{L}\p{N}\s]/gu, " ").replace(/\s+/g, " ").trim();
  const rawNames = () => $("listen-names").value.split(/[,،;\n]/).map(name => name.trim()).filter(Boolean);
  const watchedNames = () => rawNames().map(normalize).filter(Boolean);
  const displayName = name => rawNames().find(item => normalize(item) === name) || name;
  const latinKey = value => value.replace(/[aeiouy]/g, "");
  function distance(a, b) { const row = Array.from({ length: b.length + 1 }, (_, i) => i); for (let i = 1; i <= a.length; i += 1) { let previous = row[0]; row[0] = i; for (let j = 1; j <= b.length; j += 1) { const saved = row[j]; row[j] = Math.min(row[j] + 1, row[j - 1] + 1, previous + (a[i - 1] === b[j - 1] ? 0 : 1)); previous = saved; } } return row[b.length]; }
  function closeWord(word, name) { if (word === name) return true; if (name.length < 4 || word.length < 4) return false; if (word.includes(name) || name.includes(word)) return Math.min(word.length, name.length) >= name.length - 1; if (/^[a-z]+$/.test(word) && /^[a-z]+$/.test(name) && latinKey(word) === latinKey(name)) return true; return distance(word, name) <= Math.max(1, Math.floor(name.length * .2)); }
  function matchedName(text) { const full = normalize(text); for (const name of watchedNames()) { if (full.includes(name)) return name; const nameWords = name.split(" "), heardWords = full.split(" "); if (nameWords.length === 1 && heardWords.some(word => closeWord(word, name))) return name; for (let i = 0; i <= heardWords.length - nameWords.length; i += 1) if (nameWords.every((word, index) => closeWord(heardWords[i + index], word))) return name; } return ""; }
  const languages = () => { const names = $("listen-names").value, ar = /[\u0600-\u06FF]/.test(names), en = /[A-Za-z]/.test(names); return ar && en ? ["ar-SA", "en-US"] : [ar ? "ar-SA" : "en-US"]; };
  const minutes = value => { const [h, m] = (value || "").split(":").map(Number); return Number.isInteger(h) && Number.isInteger(m) ? h * 60 + m : null; };
  const hasSchedule = () => Boolean($("listen-start").value && $("listen-end").value && $("listen-start").value !== $("listen-end").value);
  const dailySchedule = () => $("listen-daily").checked;
  const scheduleId = () => `${new Date().toDateString()}|${$("listen-start").value}|${$("listen-end").value}`;
  const scheduleDone = () => !dailySchedule() && localStorage.mobileScheduleDone === scheduleId();
  const finishSchedule = () => { if (!dailySchedule()) localStorage.mobileScheduleDone = scheduleId(); };
  const scheduledNow = () => { const start = minutes($("listen-start").value), end = minutes($("listen-end").value); if (start === null || end === null || start === end) return false; const d = new Date(), now = d.getHours() * 60 + d.getMinutes(); return start < end ? now >= start && now < end : now >= start || now < end; };
  const scheduleEnded = () => { const start = minutes($("listen-start").value), end = minutes($("listen-end").value), nowDate = new Date(), now = nowDate.getHours() * 60 + nowDate.getMinutes(); return start !== null && end !== null && start < end && now >= end; };
  function armScheduledStop() { clearTimeout(scheduleStopTimer); if (!hasSchedule() || scheduleDone() || !scheduledNow()) return; const end = minutes($("listen-end").value), now = new Date(), target = new Date(now); target.setHours(Math.floor(end / 60), end % 60, 0, 0); if (target <= now) target.setDate(target.getDate() + 1); scheduleStopTimer = setTimeout(() => { if (listening) stop(true); finishSchedule(); tick(); }, Math.max(500, target - now)); }
  function problem(error) { const code = error?.error || error?.name || ""; if (["not-allowed", "NotAllowedError", "service-not-allowed"].includes(code)) return "اسمح بالميكروفون من رمز القفل بجانب الرابط، ثم حدّث الصفحة."; if (["not-found", "NotFoundError"].includes(code)) return "لا يوجد ميكروفون متاح في الكمبيوتر."; if (["not-readable", "NotReadableError"].includes(code)) return "الميكروفون مستخدم في برنامج آخر."; if (code === "network") return "تعذر تشغيل خدمة التعرف. تأكد من الإنترنت."; return `تعذر بدء الاستماع: ${code || "خطأ غير معروف"}`; }
  function ring() { const context = new AudioContext(), gain = context.createGain(); gain.gain.value = .35; gain.connect(context.destination); for (let i = 0; i < 8; i += 1) { const tone = context.createOscillator(); tone.frequency.value = i % 2 ? 1180 : 880; tone.connect(gain); tone.start(context.currentTime + i * .16); tone.stop(context.currentTime + i * .16 + .1); } setTimeout(() => context.close(), 1500); }
  function stopRing() { const context = new AudioContext(), gain = context.createGain(); gain.gain.value = .28; gain.connect(context.destination); for (let i = 0; i < 3; i += 1) { const tone = context.createOscillator(); tone.frequency.value = 560; tone.connect(gain); tone.start(context.currentTime + i * .28); tone.stop(context.currentTime + i * .28 + .18); } setTimeout(() => context.close(), 1200); }
  function alertName(name = "") { const display = name || "صاحبنا", message = `🔔 يا الشيخ ${display} مثل ما وصيتنا.. سمعنا اسمك.. إذا ودك أو بكيفك 😄`, toast = $("name-toast"), boldName = document.createElement("strong"); boldName.textContent = display; status(message); toast.replaceChildren("🔔 يا الشيخ ", boldName, " مثل ما وصيتنا.. سمعنا اسمك.. إذا ودك أو بكيفك 😄"); toast.hidden = false; clearTimeout(toastTimer); toastTimer = setTimeout(() => { toast.hidden = true; }, 8000); ring(); navigator.vibrate?.([180, 90, 180, 90, 180]); }
  async function sendTelegram(text, isTest = false) { const token = $("telegram-token").value.trim(), chatId = $("telegram-chat-id").value.trim(); if (!token || !chatId) { if (isTest) $("telegram-status").textContent = "اكتب Bot Token وChat ID أولًا."; return; } try { $("telegram-status").textContent = isTest ? "جارٍ إرسال الاختبار..." : "جارٍ إرسال التنبيه للجوال..."; const body = new URLSearchParams({ chat_id: chatId, text }); const response = await fetch(`https://api.telegram.org/bot${token}/sendMessage`, { method: "POST", body }); const data = await response.json(); if (!response.ok || !data.ok) throw new Error(data?.description || "تعذر الإرسال"); $("telegram-status").textContent = isTest ? "نجح الاختبار. وصلتك رسالة Telegram." : "تم إرسال تنبيه Telegram."; } catch (error) { $("telegram-status").textContent = `تعذر إرسال Telegram: ${error.message || "تحقق من البيانات والإنترنت"}`; } }
  async function sendTelegramFile(file, caption = "ملف من Smart Guardian") { const token = $("telegram-token").value.trim(), chatId = $("telegram-chat-id").value.trim(); if (!token || !chatId) { $("telegram-status").textContent = "اكتب Bot Token وChat ID أولًا."; return false; } if (!file) { $("telegram-status").textContent = "اختر ملفًا أولًا."; return false; } if (file.size > 50 * 1024 * 1024) { $("telegram-status").textContent = "حجم الملف أكبر من 50 MB؛ اختر ملفًا أصغر."; return false; } try { $("telegram-status").textContent = "جارٍ إرسال الملف إلى Telegram..."; const body = new FormData(); body.append("chat_id", chatId); body.append("caption", caption); body.append("document", file, file.name || "smart-guardian-file"); const response = await fetch(`https://api.telegram.org/bot${token}/sendDocument`, { method: "POST", body }); const data = await response.json(); if (!response.ok || !data.ok) throw new Error(data?.description || "تعذر الإرسال"); $("telegram-status").textContent = "تم إرسال الملف. ستجده الآن في جميع أجهزتك على Telegram."; return { ok: true, fileId: data.result?.document?.file_id || "" }; } catch (error) { $("telegram-status").textContent = `تعذر إرسال الملف: ${error.message || "تحقق من الربط والإنترنت"}`; return false; } }
  function alertTelegram(name) { if (!$("telegram-enabled").checked) return; sendTelegram(`عزيزي ${name || "طالبنا"}، الرجاء الانتباه.. سمعنا اسمك الآن.`); }
  function saveTelegram() { localStorage.telegramToken = $("telegram-token").value.trim(); localStorage.telegramChatId = $("telegram-chat-id").value.trim(); localStorage.telegramEnabled = $("telegram-enabled").checked ? "1" : "0"; $("telegram-status").textContent = "تم حفظ الربط على هذا الجهاز."; }
  function clearTelegram() { ["telegramToken", "telegramChatId", "telegramEnabled"].forEach(key => localStorage.removeItem(key)); $("telegram-token").value = ""; $("telegram-chat-id").value = ""; $("telegram-enabled").checked = false; $("telegram-status").textContent = "تم مسح ربط Telegram من هذا الجهاز."; }
  const screenStatus = text => { $("screen-monitor-status").textContent = text; };
  function sensitivityLabel() { const value = Number($("screen-sensitivity").value); $("screen-sensitivity-label").textContent = value <= 11 ? "عالية — تلتقط تغيّرات أصغر" : value >= 27 ? "منخفضة — تتجاهل الحركة البسيطة" : "متوازنة"; localStorage.screenSensitivity = String(value); }
  function paintScreenSelection() { const video = $("screen-preview"), marker = $("screen-selection"); if (!screenSelection || !video.clientWidth || !video.clientHeight) return marker.hidden = true; const { x, y, w, h } = screenSelection; marker.hidden = false; marker.style.left = `${video.offsetLeft + x * video.clientWidth}px`; marker.style.top = `${video.offsetTop + y * video.clientHeight}px`; marker.style.width = `${w * video.clientWidth}px`; marker.style.height = `${h * video.clientHeight}px`; }
  function selectScreenArea(event) { const video = $("screen-preview"), rect = video.getBoundingClientRect(); if (event.clientX < rect.left || event.clientX > rect.right || event.clientY < rect.top || event.clientY > rect.bottom) return null; return { x: Math.max(0, Math.min(1, (event.clientX - rect.left) / rect.width)), y: Math.max(0, Math.min(1, (event.clientY - rect.top) / rect.height)) }; }
  function renderScreenFrame() { if (!screenMonitoring || !screenStream || !screenSelection) return; const video = $("screen-preview"); if (video.readyState < 2 || !video.videoWidth) return; const x = Math.max(0, Math.min(.98, screenSelection.x)), y = Math.max(0, Math.min(.98, screenSelection.y)), w = Math.max(.02, Math.min(1 - x, screenSelection.w)), h = Math.max(.02, Math.min(1 - y, screenSelection.h)); const canvas = document.createElement("canvas"); canvas.width = 64; canvas.height = 36; const context = canvas.getContext("2d", { willReadFrequently: true }); context.drawImage(video, x * video.videoWidth, y * video.videoHeight, w * video.videoWidth, h * video.videoHeight, 0, 0, canvas.width, canvas.height); const pixels = context.getImageData(0, 0, canvas.width, canvas.height).data; const frame = new Uint8Array(canvas.width * canvas.height); for (let i = 0, j = 0; i < pixels.length; i += 4, j += 1) frame[j] = (pixels[i] * 54 + pixels[i + 1] * 183 + pixels[i + 2] * 19) >> 8; if (!screenLastFrame) { screenLastFrame = frame; screenStatus("تم تثبيت الصورة المرجعية. تتم مراقبة المنطقة المحددة الآن."); return; } let sum = 0; for (let i = 0; i < frame.length; i += 1) sum += Math.abs(frame[i] - screenLastFrame[i]); const difference = sum / frame.length; const threshold = Number($("screen-sensitivity").value); if (difference >= threshold) { screenChangeCount += 1; if (screenChangeCount >= 2 && Date.now() - screenLastAlert > 45000) { screenLastAlert = Date.now(); screenChangeCount = 0; screenLastFrame = frame; const text = "🔔 تنبيه الحارس الذكي: ظهر تغيّر واضح في منطقة الاستبيان التي حددتها. افتح المحاضرة الآن."; const toast = $("screen-toast"); toast.textContent = "🔔 ظهر تغيّر جديد في منطقة الاستبيان"; toast.hidden = false; setTimeout(() => { toast.hidden = true; }, 9000); ring(); navigator.vibrate?.([180, 80, 180, 80, 180]); if ($("telegram-enabled").checked) sendTelegram(text); screenStatus("تم إرسال تنبيه للتغيّر المكتشف. تستمر المراقبة الآن."); } } else { screenChangeCount = 0; screenLastFrame = frame; } }
  function startScreenSampling() { clearInterval(screenTimer); screenLastFrame = null; screenChangeCount = 0; screenMonitoring = true; screenTimer = setInterval(renderScreenFrame, 1000); renderScreenFrame(); }
  function stopScreenMonitor(message = "تم إيقاف مراقبة الشاشة.") { screenMonitoring = false; clearInterval(screenTimer); screenTimer = null; screenLastFrame = null; screenChangeCount = 0; if (screenStream) screenStream.getTracks().forEach(track => track.stop()); screenStream = null; $("screen-preview").srcObject = null; $("screen-preview-wrap").hidden = true; $("start-screen-monitor").hidden = false; $("stop-screen-monitor").hidden = true; screenStatus(message); }
  async function startScreenMonitor() { if (!navigator.mediaDevices?.getDisplayMedia) return screenStatus("متصفحك لا يدعم اختيار تبويب للمراقبة. افتح الرابط المنشور في Chrome أو Edge."); if (!window.isSecureContext && location.protocol !== "file:") return screenStatus("افتح الرابط المنشور عبر HTTPS لتفعيل مراقبة الشاشة."); try { screenStatus("اختر تبويب المحاضرة من النافذة، ثم اسمح بالمشاركة."); const stream = await navigator.mediaDevices.getDisplayMedia({ video: { frameRate: { ideal: 3, max: 5 } }, audio: false }); screenStream = stream; const video = $("screen-preview"); video.srcObject = stream; await video.play(); $("screen-preview-wrap").hidden = false; $("start-screen-monitor").hidden = true; $("stop-screen-monitor").hidden = false; screenSelection = null; paintScreenSelection(); stream.getVideoTracks()[0].onended = () => { if (screenStream === stream) stopScreenMonitor("توقفت مشاركة التبويب، لذلك توقفت المراقبة."); }; screenStatus("اسحب فوق معاينة تبويب المحاضرة لتحديد شريط الاستبيان. بعدها تبدأ المراقبة تلقائيًا."); } catch (error) { screenStatus(error?.name === "NotAllowedError" ? "لم تسمح بمشاركة تبويب المحاضرة؛ لن تبدأ المراقبة." : "تعذر بدء مراقبة الشاشة. حاول اختيار تبويب المحاضرة مرة أخرى."); } }
  function setupScreenSelection() { const wrap = $("screen-preview-wrap"); wrap.addEventListener("pointerdown", event => { const point = selectScreenArea(event); if (!point || !screenStream) return; screenDrag = point; screenSelection = { x: point.x, y: point.y, w: .01, h: .01 }; wrap.setPointerCapture?.(event.pointerId); paintScreenSelection(); }); wrap.addEventListener("pointermove", event => { if (!screenDrag) return; const point = selectScreenArea(event); if (!point) return; screenSelection = { x: Math.min(screenDrag.x, point.x), y: Math.min(screenDrag.y, point.y), w: Math.max(.02, Math.abs(point.x - screenDrag.x)), h: Math.max(.02, Math.abs(point.y - screenDrag.y)) }; paintScreenSelection(); }); const done = () => { if (!screenDrag) return; screenDrag = null; paintScreenSelection(); startScreenSampling(); }; wrap.addEventListener("pointerup", done); wrap.addEventListener("pointercancel", done); window.addEventListener("resize", paintScreenSelection); }
  async function checkMicPermission() { try { const permission = await navigator.permissions?.query({ name: "microphone" }); if (!permission) return; micReady = permission.state === "granted"; permission.onchange = () => { micReady = permission.state === "granted"; }; } catch (_) {} }
  function session() { const list = languages(), activeRecognition = new Recognition(); recognition = activeRecognition; activeRecognition.continuous = true; activeRecognition.interimResults = true; activeRecognition.maxAlternatives = 3; activeRecognition.lang = list[0]; activeRecognition.onresult = event => { if (recognition !== activeRecognition) return; let text = ""; for (let i = event.resultIndex; i < event.results.length; i += 1) text += `${event.results[i][0].transcript} `; text = normalize(text); if (!text) return; heardBuffer = normalize(`${heardBuffer} ${text}`).slice(-360); $("heard").textContent = `آخر ما سمعه: ${heardBuffer}`; window.dispatchEvent(new CustomEvent("smartguardian:heard", { detail: { text } })); const name = matchedName(`${heardBuffer} ${text}`); if (name && Date.now() - listenStartedAt >= 1000 && Date.now() - lastAlert >= 5000) { lastAlert = Date.now(); const display = displayName(name); status(`تم اكتشاف الاسم: ${name}`); alertTelegram(display); alertName(display); heardBuffer = ""; } }; activeRecognition.onerror = error => { if (recognition === activeRecognition && !["no-speech", "aborted"].includes(error.error)) status(problem(error)); }; activeRecognition.onend = () => { if (recognition !== activeRecognition || !listening) return; listening = false; browserStopped = true; $("listen").textContent = "🎧 بدء متابعة الاسم"; status("أوقف المتصفح الاستماع. اضغط بدء المتابعة مرة واحدة فقط لإعادته."); }; activeRecognition.start(); }
  async function start(fromSchedule = false) { if (!Recognition) return status("التعرف الصوتي غير متاح في هذا المتصفح. استخدم Chrome."); if (!watchedNames().length && !window.studyGuardianPdfListening) return status("اكتب الاسم أولًا، أو جهّز ملف PDF لتفعيل التقاط عبارات المحاضرة."); if (fromSchedule && !micReady) return status("الجدول ينتظر إذن الميكروفون. اضغط «بدء متابعة الاسم» بنفسك مرة واحدة فقط."); if (listening || starting) return; starting = true; try { const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); stream.getTracks().forEach(track => track.stop()); micReady = true; } catch (error) { micReady = false; starting = false; return status(problem(error)); } try { browserStopped = false; heardBuffer = ""; listenStartedAt = Date.now(); listening = true; session(); $("listen").textContent = "🎧 إيقاف متابعة الاسم"; status(window.studyGuardianPdfListening ? "يستمع الحارس لعبارات المحاضرة المهمة." : (languages().length > 1 ? "تتم متابعة الاسم باللغة الأساسية المكتوبة." : "تتم متابعة الاسم من ميكروفون هذا الجهاز.")); localStorage.mobileNames = $("listen-names").value; } catch (error) { listening = false; status(problem(error)); } starting = false; }
  function stop(fromSchedule = false) { listening = false; browserStopped = true; clearTimeout(scheduleStopTimer); recognition?.stop(); if ($("stop-alarm").checked) stopRing(); $("listen").textContent = "🎧 بدء متابعة الاسم"; status(fromSchedule ? "تم إيقاف الاستماع لانتهاء الوقت المحدد." : "تم إيقاف المتابعة مباشرة."); }
  function saveSchedule(changed = false) { localStorage.mobileListenStart = $("listen-start").value; localStorage.mobileListenEnd = $("listen-end").value; localStorage.mobileListenDaily = dailySchedule() ? "1" : "0"; if (changed) localStorage.removeItem("mobileScheduleDone"); if (!hasSchedule()) { clearTimeout(scheduleStopTimer); return $("schedule-status").textContent = "اختر وقت بداية ونهاية مختلفين. لمسح الجدول امسح أحد الوقتين."; } $("schedule-status").textContent = dailySchedule() ? `يتكرر يوميًا: ${$("listen-start").value} إلى ${$("listen-end").value}.` : `مؤقت للحصة الحالية: ${$("listen-start").value} إلى ${$("listen-end").value}. بعد النهاية يتعطل حتى تغيّر الوقت.`; armScheduledStop(); }
  function tick() { if (!hasSchedule()) { clearTimeout(scheduleStopTimer); return; } if (scheduleDone()) return; if (scheduledNow()) { if (!listening && !browserStopped) start(true); armScheduledStop(); return; } if (!dailySchedule() && scheduleEnded()) { if (listening) stop(true); finishSchedule(); clearTimeout(scheduleStopTimer); $("schedule-status").textContent = "انتهى مؤقت هذه الحصة ولن يتدخل مرة أخرى حتى تغيّر الوقت."; return; } if (dailySchedule() && listening) stop(true); if (dailySchedule() && !scheduledNow()) browserStopped = false; }
  function rotate(index = 0) { quoteIndex = index % quotes.length; const quote = quotes[quoteIndex], translation = $("quote-translation"), reference = $("quote-reference"), box = $("quote-text").parentElement; $("quote-text").textContent = quote[0]; translation.textContent = quote[1]; translation.dir = /[\u0600-\u06FF]/.test(quote[1]) ? "rtl" : "ltr"; translation.hidden = !quote[1]; reference.textContent = quote[2] || ""; reference.hidden = !quote[2]; box.classList.toggle("is-verse", quote[3] === "verse"); box.classList.toggle("is-prayer", quote[3] === "prayer"); clearTimeout(quoteTimer); quoteTimer = setTimeout(() => rotate(quoteIndex + 1), 18000); }
  function cycleDesignerPrayer(index = 0) { const prayers = ["اللهم بارك لمن صمم هذه الأداة، واجزه خيرًا، وافتح له أبواب العلم والرزق والتوفيق.", "اللهم اجعل هذه الأداة نافعة، واكتب الأجر لمن ساهم في صنعها.", "اللهم يسر لصاحب هذه الأداة أمره، وبارك له في علمه ووقته.", "اللهم ارزق من صمم هذه الأداة التوفيق والسداد والخير الكثير."]; $("designer-prayer").textContent = prayers[index % prayers.length]; setTimeout(() => cycleDesignerPrayer(index + 1), 18000); }
  $("listen-names").value = localStorage.mobileNames || ""; $("listen-start").value = localStorage.mobileListenStart || ""; $("listen-end").value = localStorage.mobileListenEnd || ""; $("listen-daily").checked = localStorage.mobileListenDaily === "1"; $("stop-alarm").checked = localStorage.mobileStopAlarm !== "0"; $("telegram-token").value = localStorage.telegramToken || ""; $("telegram-chat-id").value = localStorage.telegramChatId || ""; $("telegram-enabled").checked = localStorage.telegramEnabled === "1";
  ["courseName", "courseContext", "geminiKey", "courseAiEnabled"].forEach(key => localStorage.removeItem(key));
  $("screen-sensitivity").value = localStorage.screenSensitivity || "14"; sensitivityLabel(); $("screen-sensitivity").oninput = sensitivityLabel; $("start-screen-monitor").onclick = startScreenMonitor; $("stop-screen-monitor").onclick = () => stopScreenMonitor(); setupScreenSelection();
  const gpaGrades = { "5": [["A+", 5], ["A", 4.75], ["B+", 4.5], ["B", 4], ["C+", 3.5], ["C", 3], ["D+", 2.5], ["D", 2], ["F", 0]], "4": [["A", 4], ["B+", 3.5], ["B", 3], ["C+", 2.5], ["C", 2], ["D+", 1.5], ["D", 1], ["F", 0]] };
  const savedGpaCourses = () => { try { const items = JSON.parse(localStorage.gpaCourses || "[]"); return Array.isArray(items) ? items.slice(0, 20) : []; } catch (_) { return []; } };
  function saveGpaCourses() { const courses = [...$("gpa-courses").querySelectorAll(".gpa-course")].map(row => ({ name: row.querySelector(".gpa-name").value.trim(), hours: row.querySelector(".gpa-hours").value, grade: row.querySelector(".gpa-grade").value })); localStorage.gpaCourses = JSON.stringify(courses); }
  function makeGpaCourse(course = {}) { const scale = $("gpa-scale").value, row = document.createElement("div"), name = document.createElement("input"), hours = document.createElement("input"), grade = document.createElement("select"), remove = document.createElement("button"); row.className = "gpa-course"; name.className = "gpa-name"; name.placeholder = "اسم المادة"; name.value = course.name || ""; hours.className = "gpa-hours"; hours.type = "number"; hours.min = "1"; hours.max = "12"; hours.step = "1"; hours.value = course.hours || "3"; grade.className = "gpa-grade"; const placeholder = document.createElement("option"); placeholder.value = ""; placeholder.textContent = "الدرجة"; grade.append(placeholder); gpaGrades[scale].forEach(([label, points]) => { const option = document.createElement("option"); option.value = String(points); option.textContent = `${label} — ${points}`; if (String(points) === String(course.grade)) option.selected = true; grade.append(option); }); remove.type = "button"; remove.title = "حذف المادة"; remove.setAttribute("aria-label", "حذف المادة"); remove.textContent = "×"; remove.onclick = () => { row.remove(); saveGpaCourses(); }; [["المادة", name], ["الساعات", hours], ["الدرجة", grade]].forEach(([text, control]) => { const label = document.createElement("label"); label.textContent = text; label.append(control); row.append(label); }); row.append(remove); row.oninput = saveGpaCourses; row.onchange = saveGpaCourses; return row; }
  function renderGpaCourses(courses = savedGpaCourses()) { const target = $("gpa-courses"); target.replaceChildren(); (courses.length ? courses : [{}, {}, {}]).forEach(course => target.append(makeGpaCourse(course))); $("gpa-result").textContent = "أضف المواد ثم احسب المعدل."; }
  function calculateGpa() { saveGpaCourses(); const scale = Number($("gpa-scale").value), courses = savedGpaCourses(), valid = courses.filter(course => Number(course.hours) > 0 && course.grade !== ""); if (!valid.length) return $("gpa-result").textContent = "اختر ساعات ودرجة مادة واحدة على الأقل."; const hours = valid.reduce((sum, course) => sum + Number(course.hours), 0), points = valid.reduce((sum, course) => sum + Number(course.hours) * Number(course.grade), 0), result = points / hours; $("gpa-result").textContent = `معدلك الحالي: ${result.toFixed(2)} من ${scale} — مجموع الساعات: ${hours}`; }
  $("gpa-scale").value = localStorage.gpaScale === "4" ? "4" : "5"; $("gpa-scale").onchange = () => { localStorage.gpaScale = $("gpa-scale").value; renderGpaCourses(savedGpaCourses().map(course => ({ ...course, grade: "" }))); }; $("add-gpa-course").onclick = () => { $("gpa-courses").append(makeGpaCourse()); saveGpaCourses(); }; $("calculate-gpa").onclick = calculateGpa; renderGpaCourses();
  window.studyGuardianSendTelegramFile = sendTelegramFile;
  $("listen").onclick = () => listening ? stop() : start(); $("listen-start").onchange = () => saveSchedule(true); $("listen-end").onchange = () => saveSchedule(true); $("listen-daily").onchange = () => saveSchedule(true); $("stop-alarm").onchange = () => { localStorage.mobileStopAlarm = $("stop-alarm").checked ? "1" : "0"; }; $("save-telegram").onclick = saveTelegram; $("test-telegram").onclick = () => sendTelegram("تم ربط Study Guardian بنجاح.", true); $("send-telegram-file").onclick = () => sendTelegramFile($("telegram-file").files?.[0]); $("clear-telegram").onclick = clearTelegram; $("previous-quote").onclick = () => rotate((quoteIndex - 1 + quotes.length) % quotes.length); $("next-quote").onclick = () => rotate(quoteIndex + 1);
  const prayerNames = { Fajr: "الفجر", Dhuhr: "الظهر", Asr: "العصر", Maghrib: "المغرب", Isha: "العشاء" };
  const prayerKeys = Object.keys(prayerNames);
  const cleanPrayerTime = value => (value || "").match(/\d{2}:\d{2}/)?.[0] || "";
  const timeParts = time => time.split(":").map(Number);
  const timeValue = time => { const [hour, minute] = timeParts(time); return hour * 60 + minute; };
  const manualPrayerIds = { Fajr: "manual-fajr", Dhuhr: "manual-dhuhr", Asr: "manual-asr", Maghrib: "manual-maghrib", Isha: "manual-isha" };
  const savedManualPrayerTimes = () => { try { return JSON.parse(localStorage.prayerManualTimes || "{}"); } catch (_) { return {}; } };
  const hasCompleteManualPrayerTimes = times => prayerKeys.every(key => /^\d{2}:\d{2}$/.test(times[key] || ""));
  function useManualPrayerTimes(times) { prayerData = { city: "الأوقات اليدوية", zone: Intl.DateTimeFormat().resolvedOptions().timeZone || "Asia/Riyadh", date: new Date().toISOString().slice(0, 10), baseTimes: { ...times }, times: { ...times } }; }
  function applyManualPrayerTimes() { if (!prayerData) return; const manual = savedManualPrayerTimes(); prayerData.times = Object.fromEntries(prayerKeys.map(key => [key, /^\d{2}:\d{2}$/.test(manual[key] || "") ? manual[key] : prayerData.baseTimes[key]])); }
  function fillManualPrayerInputs() { if (!prayerData) return; const manual = savedManualPrayerTimes(); prayerKeys.forEach(key => { $(manualPrayerIds[key]).value = manual[key] || prayerData.baseTimes[key] || ""; }); }
  function saveManualPrayerTimes() { const times = {}; for (const key of prayerKeys) { const value = $(manualPrayerIds[key]).value; if (!/^\d{2}:\d{2}$/.test(value)) return $("prayer-status").textContent = "أكمل أوقات الصلوات الخمس أولًا."; times[key] = value; } localStorage.prayerManualTimes = JSON.stringify(times); if (!prayerData) useManualPrayerTimes(times); else applyManualPrayerTimes(); renderPrayerTimes(); checkPrayerTimes(); $("prayer-status").textContent = "تم حفظ الأوقات اليدوية، ويظهر عداد الصلاة القادمة الآن."; }
  function resetManualPrayerTimes() { localStorage.removeItem("prayerManualTimes"); if (!prayerData) return $("prayer-status").textContent = "ستعود للمواقيت التلقائية عند تحديث المدينة أو الموقع."; applyManualPrayerTimes(); fillManualPrayerInputs(); renderPrayerTimes(); checkPrayerTimes(); $("prayer-status").textContent = "تمت العودة للمواقيت التلقائية."; }
  function cityClock() { if (!prayerData) return ""; return new Intl.DateTimeFormat("en-GB", { timeZone: prayerData.zone, hour: "2-digit", minute: "2-digit", hour12: false }).format(new Date()); }
  function showPrayerToast(text) { const toast = $("prayer-toast"); toast.textContent = text; toast.hidden = false; clearTimeout(prayerToastTimer); prayerToastTimer = setTimeout(() => { toast.hidden = true; }, 12000); try { ring(); } catch (_) {} navigator.vibrate?.([200, 100, 200]); }
  function renderPrayerTimes() { if (!prayerData) return; const now = cityClock(), current = timeValue(now), items = prayerKeys.map(key => ({ key, time: prayerData.times[key] })); let next = items.find(item => timeValue(item.time) >= current); let tomorrow = false; if (!next) { next = items[0]; tomorrow = true; } let remaining = timeValue(next.time) - current; if (remaining < 0) remaining += 1440; const hours = Math.floor(remaining / 60), minutes = remaining % 60, wait = `${hours ? `${hours} ساعة ` : ""}${minutes} دقيقة`; $("prayer-title").textContent = `الصلاة القادمة: ${prayerNames[next.key]}`; $("prayer-countdown").textContent = `باقي ${wait}${tomorrow ? " — غدًا" : ""}.`; $("prayer-status").textContent = `حسب مدينة ${prayerData.city}. الصلاة القادمة الساعة ${next.time}.`; $("prayer-times").textContent = items.map(item => `${prayerNames[item.key]}: ${item.time}`).join("  •  "); $("prayer-times").hidden = false; }
  async function fetchPrayerTimes(url, city, failureMessage) { $("prayer-status").textContent = "جارٍ جلب مواقيت الصلاة..."; try { const response = await fetch(url); const result = await response.json(); if (!response.ok || result.code !== 200) throw new Error("تعذر جلب المواقيت"); const timings = {}; prayerKeys.forEach(key => { timings[key] = cleanPrayerTime(result.data.timings[key]); }); prayerData = { city, zone: result.data.meta.timezone, date: result.data.date.gregorian.date, baseTimes: timings, times: timings }; applyManualPrayerTimes(); fillManualPrayerInputs(); renderPrayerTimes(); checkPrayerTimes(); } catch (_) { $("prayer-status").textContent = failureMessage; } }
  async function loadPrayerTimes() { const city = $("prayer-city").value.trim(), country = $("prayer-country").value.trim(); localStorage.prayerCity = city; localStorage.prayerCountry = country; localStorage.prayerEnabled = $("prayer-enabled").checked ? "1" : "0"; localStorage.removeItem("prayerLatitude"); localStorage.removeItem("prayerLongitude"); if (!city || !country) return $("prayer-status").textContent = "اكتب المدينة والدولة أولًا."; return fetchPrayerTimes(`https://api.aladhan.com/v1/timingsByCity?city=${encodeURIComponent(city)}&country=${encodeURIComponent(country)}&method=4`, city, "تعذر جلب المواقيت. تحقق من اسم المدينة والإنترنت."); }
  function loadPrayerTimesByLocation(latitude, longitude) { localStorage.prayerLatitude = String(latitude); localStorage.prayerLongitude = String(longitude); localStorage.prayerEnabled = $("prayer-enabled").checked ? "1" : "0"; return fetchPrayerTimes(`https://api.aladhan.com/v1/timings?latitude=${encodeURIComponent(latitude)}&longitude=${encodeURIComponent(longitude)}&method=4`, "موقعك الحالي", "تعذر جلب المواقيت من موقعك. تحقق من الإنترنت أو استخدم المدينة يدويًا."); }
  function useCurrentLocation() { if (!navigator.geolocation) return $("prayer-status").textContent = "تحديد الموقع غير مدعوم في هذا المتصفح."; $("prayer-status").textContent = "بانتظار إذن تحديد الموقع..."; navigator.geolocation.getCurrentPosition(position => loadPrayerTimesByLocation(position.coords.latitude, position.coords.longitude), () => { $("prayer-status").textContent = "لم يتم السماح بتحديد الموقع. يمكنك كتابة المدينة يدويًا."; }, { enableHighAccuracy: false, timeout: 10000, maximumAge: 3600000 }); }
  function checkPrayerTimes() { if (!prayerData) return; renderPrayerTimes(); if (!$("prayer-enabled").checked) return; const now = cityClock(); for (const key of prayerKeys) { const time = prayerData.times[key], alertKey = `${prayerData.date}|${key}|${time}`; if (time === now && localStorage.prayerLastAlert !== alertKey) { localStorage.prayerLastAlert = alertKey; showPrayerToast(`لقد حان وقت صلاة ${prayerNames[key]} في ${prayerData.city}.`); } } }
  function fallbackNotes() {
    const notesBox = $("notes"), render = entry => { const item = document.createElement("article"), time = document.createElement("small"); item.className = "note"; item.textContent = `[${entry.mode || "مستقل"}] ${entry.author || "طالب"}: ${entry.text}`; time.textContent = new Date(entry.createdAt || Date.now()).toLocaleString("ar-SA"); item.append(time); notesBox.prepend(item); while (notesBox.children.length > 2) notesBox.lastElementChild.remove(); };
    const stored = () => JSON.parse(localStorage.mobileNotes || "[]");
    if (!notesBox.children.length) stored().slice().reverse().forEach(render);
    $("save").onclick = () => { const text = $("note").value.trim(); if (!text) return $("note-status").textContent = "اكتب الملاحظة أولًا."; const entry = { text, author: "طالب", createdAt: Date.now(), mode: "مستقل" }, all = stored(); all.unshift(entry); localStorage.mobileNotes = JSON.stringify(all.slice(0, 100)); render(entry); $("note").value = ""; $("note-status").textContent = "تم حفظ الملاحظة."; };
    $("export-notes").onclick = () => { const entries = stored(); if (!entries.length) return $("note-status").textContent = "لا توجد ملاحظات لتصديرها."; const text = entries.map(entry => `${new Date(entry.createdAt).toLocaleString("ar-SA")}\n${entry.text}`).join("\n\n--------------------\n\n"), url = URL.createObjectURL(new Blob([text], { type: "text/plain;charset=utf-8" })), link = document.createElement("a"); link.href = url; link.download = `study-guardian-notes-${new Date().toISOString().slice(0, 10)}.txt`; document.body.append(link); link.click(); link.remove(); setTimeout(() => URL.revokeObjectURL(url), 1500); $("note-status").textContent = "تم تجهيز ملف الملاحظات."; };
    $("print-notes").onclick = () => { if (!stored().length) return $("note-status").textContent = "لا توجد ملاحظات لحفظها."; window.print(); };
  }
  const panels = [...document.querySelectorAll(".feature-map > details.panel")];
  panels.forEach(panel => panel.addEventListener("toggle", () => { if (panel.open) panels.forEach(other => { if (other !== panel) other.open = false; }); }));
  $("prayer-city").value = localStorage.prayerCity || ""; $("prayer-country").value = localStorage.prayerCountry || ""; $("prayer-enabled").checked = localStorage.prayerEnabled === "1"; $("update-prayers").onclick = loadPrayerTimes; $("use-location").onclick = useCurrentLocation; $("save-manual-prayers").onclick = saveManualPrayerTimes; $("reset-manual-prayers").onclick = resetManualPrayerTimes; $("prayer-enabled").onchange = () => { localStorage.prayerEnabled = $("prayer-enabled").checked ? "1" : "0"; if ($("prayer-enabled").checked && !prayerData) { const latitude = localStorage.prayerLatitude, longitude = localStorage.prayerLongitude; if (latitude && longitude) loadPrayerTimesByLocation(latitude, longitude); else loadPrayerTimes(); } if (!$("prayer-enabled").checked && prayerData) renderPrayerTimes(); }; { const latitude = localStorage.prayerLatitude, longitude = localStorage.prayerLongitude, manual = savedManualPrayerTimes(); if (latitude && longitude) loadPrayerTimesByLocation(latitude, longitude); else if ($("prayer-city").value && $("prayer-country").value) loadPrayerTimes(); else if (hasCompleteManualPrayerTimes(manual)) { useManualPrayerTimes(manual); fillManualPrayerInputs(); renderPrayerTimes(); } }
  checkMicPermission(); saveSchedule(); setInterval(tick, 1000); setInterval(checkPrayerTimes, 15000); document.addEventListener("visibilitychange", () => { if (!document.hidden) { checkMicPermission(); tick(); checkPrayerTimes(); } }); window.addEventListener("focus", tick); tick(); rotate(); cycleDesignerPrayer(); window.studyGuardianCoreReady = true; setTimeout(() => { if (!window.studyGuardianMobileReady) fallbackNotes(); }, 3000);
})();
