import { initializeApp } from "https://www.gstatic.com/firebasejs/12.15.0/firebase-app.js";
import { getAuth, onAuthStateChanged, signInAnonymously } from "https://www.gstatic.com/firebasejs/12.15.0/firebase-auth.js";
import { getDatabase, ref, onValue } from "https://www.gstatic.com/firebasejs/12.15.0/firebase-database.js";

const config = { apiKey:"AIzaSyAUjRlZmePLlKKRDS8JdM4i9r0eCXcnoek", authDomain:"study-guardian-groups.firebaseapp.com", databaseURL:"https://study-guardian-groups-default-rtdb.asia-southeast1.firebasedatabase.app", projectId:"study-guardian-groups", storageBucket:"study-guardian-groups.firebasestorage.app", messagingSenderId:"499313905189", appId:"1:499313905189:web:589c4dfade509c853779cc" };
const app = initializeApp(config), auth = getAuth(app), db = getDatabase(app), box = document.getElementById("all-responses");
const ids = () => { try { const saved = JSON.parse(localStorage.mobileFeedbackIds || "[]"); const legacy = localStorage.mobileFeedbackId; return [...new Set([...(Array.isArray(saved) ? saved : []), ...(legacy ? [legacy] : [])])]; } catch (_) { return localStorage.mobileFeedbackId ? [localStorage.mobileFeedbackId] : []; } };
const records = new Map();
function render() { const replies = [...records.values()].filter(item => item.reply).sort((a,b) => (b.repliedAt || 0) - (a.repliedAt || 0)); box.replaceChildren(); if (!replies.length) { box.innerHTML = '<p class="hint">لا توجد ردود إدارة محفوظة على هذا الجهاز حتى الآن.</p>'; return; } replies.forEach(item => { const card = document.createElement("article"); card.className = "response-card"; const title = document.createElement("strong"); title.textContent = "رد إدارة الحارس الذكي"; const reply = document.createElement("p"); reply.textContent = item.reply; const time = document.createElement("small"); time.textContent = item.repliedAt ? new Date(item.repliedAt).toLocaleString("ar-SA") : ""; card.append(title, reply, time); box.append(card); }); }
document.getElementById("back-home").onclick = () => { if (history.length > 1) history.back(); else location.href = "index.html"; };
onAuthStateChanged(auth, async user => { if (!user) { try { await signInAnonymously(auth); } catch (_) { box.innerHTML = '<p class="hint">تعذر التحقق من الردود. تأكد من الإنترنت ثم أعد المحاولة.</p>'; } return; } const list = ids(); if (!list.length) return render(); list.forEach(id => onValue(ref(db, `feedback/${id}`), item => { if (item.exists()) records.set(id, item.val()); render(); }, () => render())); });
